### ISSUE TITLE
Logging weird errors on the browser console

### ISSUE THREAD

**Issue by midyan** [Teracycle/teracycle-pool#3]
While navigation between pages I have noticed theses errors:

* Cannot read property 'style' of null - index.html:496
* Cannot read property 'textContent' of null - inddex.html:431

Can someone confirm these errors on the browser console?

**Comment by JamesKegel** [comment]
I think this is what may be up with the "endless spinner" issue some of us have been experiencing. I'll check into it.

**Comment by JamesKegel** [comment]
(index):496 Uncaught TypeError: Cannot read property 'style' of null
    at pulseLiveUpdate ((index):496)
    at Object.<anonymous> ((index):514)
    at j (jquery.js:3073)
    at Object.fireWith [as resolveWith] (jquery.js:3185)
    at x (jquery.js:8251)
    at XMLHttpRequest.<anonymous> (jquery.js:8598)

**Comment by JamesKegel** [comment]
line 496 is `stats_update.style.transition = 'opacity 100ms ease-out';`

Let me see if disabling this helps.

**Comment by JamesKegel** [comment]
stats_update.**style**.transition  maybe this is specifically what it is complaining about

**Comment by JamesKegel** [comment]
OK, I did some testing last night, and I have narrowed this down to the little status updater that blinks at the top of most node-crypto-pool (ncp hereafter). If the little blink element isn't being shown, the JS freaks out. I had a similar problem when trying to remove some of the dynamic data stuff from pages/home.html at one point. In the next version I'll remove this.

**Comment by JamesKegel** [comment]
This is fixed. I will merge the code in as soon as I can get my main laptop up. I'm on chromebook right now, but the change is live on the main site.
