### ISSUE TITLE
Endless Spinner

### ISSUE THREAD

**Issue by JamesKegel** [Teracycle/teracycle-pool#5]
I've received a few complaints about an "endless spinner" when the front end is loading. Server logs don't indicate anything weird is happening, and I'm unable to reliably reproduce the error to view log output in Chrome dev tools.

**Comment by midyan** [comment]
I had the issue once and checked the log. It said that *hamburger_cross* function was undefined, so I believe it is a problem when loading the custom.js file

**Comment by JamesKegel** [comment]
I thought about that and am curious if it has to do with users having cached content in the browser keeping them from downloading the changes with sidebar.

**Comment by JamesKegel** [comment]
This is fixed
